//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magasin.Panier {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.spring.ubp.com/", ConfigurationName="Panier.Panier")]
    public interface Panier {
        
        // CODEGEN: Parameter 'idProduit' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magasin.Panier.DeleteItemResponse DeleteItem(Magasin.Panier.DeleteItem request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.Panier.DeleteItemResponse> DeleteItemAsync(Magasin.Panier.DeleteItem request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Magasin.Panier.getTotalResponse getTotal(Magasin.Panier.getTotal request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.Panier.getTotalResponse> getTotalAsync(Magasin.Panier.getTotal request);
        
        // CODEGEN: Parameter 'produit' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magasin.Panier.addArticleResponse addArticle(Magasin.Panier.addArticle request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.Panier.addArticleResponse> addArticleAsync(Magasin.Panier.addArticle request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Magasin.Panier.getSizeResponse getSize(Magasin.Panier.getSize request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.Panier.getSizeResponse> getSizeAsync(Magasin.Panier.getSize request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Magasin.Panier.getItemsResponse getItems(Magasin.Panier.getItems request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.Panier.getItemsResponse> getItemsAsync(Magasin.Panier.getItems request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteItem", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class DeleteItem {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idProduit;
        
        public DeleteItem() {
        }
        
        public DeleteItem(long idProduit) {
            this.idProduit = idProduit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteItemResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class DeleteItemResponse {
        
        public DeleteItemResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTotal", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class getTotal {
        
        public getTotal() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTotalResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class getTotalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public getTotalResponse() {
        }
        
        public getTotalResponse(double @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.spring.ubp.com/")]
    public partial class produit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idProduitField;
        
        private bool idProduitFieldSpecified;
        
        private string designationField;
        
        private string descriptionField;
        
        private double prixField;
        
        private int quantiteField;
        
        private bool selectedField;
        
        private byte[] photoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long idProduit {
            get {
                return this.idProduitField;
            }
            set {
                this.idProduitField = value;
                this.RaisePropertyChanged("idProduit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProduitSpecified {
            get {
                return this.idProduitFieldSpecified;
            }
            set {
                this.idProduitFieldSpecified = value;
                this.RaisePropertyChanged("idProduitSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string designation {
            get {
                return this.designationField;
            }
            set {
                this.designationField = value;
                this.RaisePropertyChanged("designation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double prix {
            get {
                return this.prixField;
            }
            set {
                this.prixField = value;
                this.RaisePropertyChanged("prix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int quantite {
            get {
                return this.quantiteField;
            }
            set {
                this.quantiteField = value;
                this.RaisePropertyChanged("quantite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool selected {
            get {
                return this.selectedField;
            }
            set {
                this.selectedField = value;
                this.RaisePropertyChanged("selected");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=6)]
        public byte[] photo {
            get {
                return this.photoField;
            }
            set {
                this.photoField = value;
                this.RaisePropertyChanged("photo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.spring.ubp.com/")]
    public partial class client : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idClientField;
        
        private bool idClientFieldSpecified;
        
        private string nomField;
        
        private string prenomField;
        
        private string adresseField;
        
        private string telField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long idClient {
            get {
                return this.idClientField;
            }
            set {
                this.idClientField = value;
                this.RaisePropertyChanged("idClient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idClientSpecified {
            get {
                return this.idClientFieldSpecified;
            }
            set {
                this.idClientFieldSpecified = value;
                this.RaisePropertyChanged("idClientSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                this.nomField = value;
                this.RaisePropertyChanged("nom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string prenom {
            get {
                return this.prenomField;
            }
            set {
                this.prenomField = value;
                this.RaisePropertyChanged("prenom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
                this.RaisePropertyChanged("adresse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string tel {
            get {
                return this.telField;
            }
            set {
                this.telField = value;
                this.RaisePropertyChanged("tel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.spring.ubp.com/")]
    public partial class commande : object, System.ComponentModel.INotifyPropertyChanged {
        
        private client clientField;
        
        private System.DateTime dateCommandeField;
        
        private bool dateCommandeFieldSpecified;
        
        private long idCommandeField;
        
        private bool idCommandeFieldSpecified;
        
        private ligneDeCommande[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public client client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
                this.RaisePropertyChanged("client");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime dateCommande {
            get {
                return this.dateCommandeField;
            }
            set {
                this.dateCommandeField = value;
                this.RaisePropertyChanged("dateCommande");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateCommandeSpecified {
            get {
                return this.dateCommandeFieldSpecified;
            }
            set {
                this.dateCommandeFieldSpecified = value;
                this.RaisePropertyChanged("dateCommandeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long idCommande {
            get {
                return this.idCommandeField;
            }
            set {
                this.idCommandeField = value;
                this.RaisePropertyChanged("idCommande");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCommandeSpecified {
            get {
                return this.idCommandeFieldSpecified;
            }
            set {
                this.idCommandeFieldSpecified = value;
                this.RaisePropertyChanged("idCommandeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("items", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public ligneDeCommande[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.spring.ubp.com/")]
    public partial class ligneDeCommande : object, System.ComponentModel.INotifyPropertyChanged {
        
        private commande commandeField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private double prixField;
        
        private produit produitField;
        
        private int quantiteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public commande commande {
            get {
                return this.commandeField;
            }
            set {
                this.commandeField = value;
                this.RaisePropertyChanged("commande");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double prix {
            get {
                return this.prixField;
            }
            set {
                this.prixField = value;
                this.RaisePropertyChanged("prix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public produit produit {
            get {
                return this.produitField;
            }
            set {
                this.produitField = value;
                this.RaisePropertyChanged("produit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int quantite {
            get {
                return this.quantiteField;
            }
            set {
                this.quantiteField = value;
                this.RaisePropertyChanged("quantite");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addArticle", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class addArticle {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Magasin.Panier.produit produit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int quantite;
        
        public addArticle() {
        }
        
        public addArticle(Magasin.Panier.produit produit, int quantite) {
            this.produit = produit;
            this.quantite = quantite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addArticleResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class addArticleResponse {
        
        public addArticleResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSize", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class getSize {
        
        public getSize() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSizeResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class getSizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public getSizeResponse() {
        }
        
        public getSizeResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getItems", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class getItems {
        
        public getItems() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getItemsResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class getItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Magasin.Panier.ligneDeCommande[] @return;
        
        public getItemsResponse() {
        }
        
        public getItemsResponse(Magasin.Panier.ligneDeCommande[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PanierChannel : Magasin.Panier.Panier, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PanierClient : System.ServiceModel.ClientBase<Magasin.Panier.Panier>, Magasin.Panier.Panier {
        
        public PanierClient() {
        }
        
        public PanierClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PanierClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PanierClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PanierClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.Panier.DeleteItemResponse Magasin.Panier.Panier.DeleteItem(Magasin.Panier.DeleteItem request) {
            return base.Channel.DeleteItem(request);
        }
        
        public void DeleteItem(long idProduit) {
            Magasin.Panier.DeleteItem inValue = new Magasin.Panier.DeleteItem();
            inValue.idProduit = idProduit;
            Magasin.Panier.DeleteItemResponse retVal = ((Magasin.Panier.Panier)(this)).DeleteItem(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.Panier.DeleteItemResponse> Magasin.Panier.Panier.DeleteItemAsync(Magasin.Panier.DeleteItem request) {
            return base.Channel.DeleteItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.Panier.DeleteItemResponse> DeleteItemAsync(long idProduit) {
            Magasin.Panier.DeleteItem inValue = new Magasin.Panier.DeleteItem();
            inValue.idProduit = idProduit;
            return ((Magasin.Panier.Panier)(this)).DeleteItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.Panier.getTotalResponse Magasin.Panier.Panier.getTotal(Magasin.Panier.getTotal request) {
            return base.Channel.getTotal(request);
        }
        
        public double getTotal() {
            Magasin.Panier.getTotal inValue = new Magasin.Panier.getTotal();
            Magasin.Panier.getTotalResponse retVal = ((Magasin.Panier.Panier)(this)).getTotal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.Panier.getTotalResponse> Magasin.Panier.Panier.getTotalAsync(Magasin.Panier.getTotal request) {
            return base.Channel.getTotalAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.Panier.getTotalResponse> getTotalAsync() {
            Magasin.Panier.getTotal inValue = new Magasin.Panier.getTotal();
            return ((Magasin.Panier.Panier)(this)).getTotalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.Panier.addArticleResponse Magasin.Panier.Panier.addArticle(Magasin.Panier.addArticle request) {
            return base.Channel.addArticle(request);
        }
        
        public void addArticle(Magasin.Panier.produit produit, int quantite) {
            Magasin.Panier.addArticle inValue = new Magasin.Panier.addArticle();
            inValue.produit = produit;
            inValue.quantite = quantite;
            Magasin.Panier.addArticleResponse retVal = ((Magasin.Panier.Panier)(this)).addArticle(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.Panier.addArticleResponse> Magasin.Panier.Panier.addArticleAsync(Magasin.Panier.addArticle request) {
            return base.Channel.addArticleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.Panier.addArticleResponse> addArticleAsync(Magasin.Panier.produit produit, int quantite) {
            Magasin.Panier.addArticle inValue = new Magasin.Panier.addArticle();
            inValue.produit = produit;
            inValue.quantite = quantite;
            return ((Magasin.Panier.Panier)(this)).addArticleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.Panier.getSizeResponse Magasin.Panier.Panier.getSize(Magasin.Panier.getSize request) {
            return base.Channel.getSize(request);
        }
        
        public int getSize() {
            Magasin.Panier.getSize inValue = new Magasin.Panier.getSize();
            Magasin.Panier.getSizeResponse retVal = ((Magasin.Panier.Panier)(this)).getSize(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.Panier.getSizeResponse> Magasin.Panier.Panier.getSizeAsync(Magasin.Panier.getSize request) {
            return base.Channel.getSizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.Panier.getSizeResponse> getSizeAsync() {
            Magasin.Panier.getSize inValue = new Magasin.Panier.getSize();
            return ((Magasin.Panier.Panier)(this)).getSizeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.Panier.getItemsResponse Magasin.Panier.Panier.getItems(Magasin.Panier.getItems request) {
            return base.Channel.getItems(request);
        }
        
        public Magasin.Panier.ligneDeCommande[] getItems() {
            Magasin.Panier.getItems inValue = new Magasin.Panier.getItems();
            Magasin.Panier.getItemsResponse retVal = ((Magasin.Panier.Panier)(this)).getItems(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.Panier.getItemsResponse> Magasin.Panier.Panier.getItemsAsync(Magasin.Panier.getItems request) {
            return base.Channel.getItemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.Panier.getItemsResponse> getItemsAsync() {
            Magasin.Panier.getItems inValue = new Magasin.Panier.getItems();
            return ((Magasin.Panier.Panier)(this)).getItemsAsync(inValue);
        }
    }
}
