//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magasin.VenteProduit {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.spring.ubp.com/", ConfigurationName="VenteProduit.VenteProduit")]
    public interface VenteProduit {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Magasin.VenteProduit.ListerProduitParCategorieResponse ListerProduitParCategorie(Magasin.VenteProduit.ListerProduitParCategorie request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.VenteProduit.ListerProduitParCategorieResponse> ListerProduitParCategorieAsync(Magasin.VenteProduit.ListerProduitParCategorie request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Magasin.VenteProduit.ListeDesClientsResponse ListeDesClients(Magasin.VenteProduit.ListeDesClients request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.VenteProduit.ListeDesClientsResponse> ListeDesClientsAsync(Magasin.VenteProduit.ListeDesClients request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Magasin.VenteProduit.RechercherProduitParIdResponse RechercherProduitParId(Magasin.VenteProduit.RechercherProduitParId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.VenteProduit.RechercherProduitParIdResponse> RechercherProduitParIdAsync(Magasin.VenteProduit.RechercherProduitParId request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Magasin.VenteProduit.ListerProduitParMotCleResponse ListerProduitParMotCle(Magasin.VenteProduit.ListerProduitParMotCle request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.VenteProduit.ListerProduitParMotCleResponse> ListerProduitParMotCleAsync(Magasin.VenteProduit.ListerProduitParMotCle request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Magasin.VenteProduit.ListeDeProduitsResponse ListeDeProduits(Magasin.VenteProduit.ListeDeProduits request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.VenteProduit.ListeDeProduitsResponse> ListeDeProduitsAsync(Magasin.VenteProduit.ListeDeProduits request);
        
        // CODEGEN: Parameter 'categorie' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magasin.VenteProduit.ModifierCategorieResponse ModifierCategorie(Magasin.VenteProduit.ModifierCategorie request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.VenteProduit.ModifierCategorieResponse> ModifierCategorieAsync(Magasin.VenteProduit.ModifierCategorie request);
        
        // CODEGEN: Parameter 'client' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magasin.VenteProduit.AjouterClientResponse AjouterClient(Magasin.VenteProduit.AjouterClient request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.VenteProduit.AjouterClientResponse> AjouterClientAsync(Magasin.VenteProduit.AjouterClient request);
        
        // CODEGEN: Parameter 'idCategorie' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magasin.VenteProduit.SupprimerCategorieResponse SupprimerCategorie(Magasin.VenteProduit.SupprimerCategorie request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.VenteProduit.SupprimerCategorieResponse> SupprimerCategorieAsync(Magasin.VenteProduit.SupprimerCategorie request);
        
        // CODEGEN: Parameter 'produit' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magasin.VenteProduit.AjouterProduitResponse AjouterProduit(Magasin.VenteProduit.AjouterProduit request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.VenteProduit.AjouterProduitResponse> AjouterProduitAsync(Magasin.VenteProduit.AjouterProduit request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Magasin.VenteProduit.RechercherClientParIdResponse RechercherClientParId(Magasin.VenteProduit.RechercherClientParId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.VenteProduit.RechercherClientParIdResponse> RechercherClientParIdAsync(Magasin.VenteProduit.RechercherClientParId request);
        
        // CODEGEN: Parameter 'categorie' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magasin.VenteProduit.AjouterCategorieResponse AjouterCategorie(Magasin.VenteProduit.AjouterCategorie request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.VenteProduit.AjouterCategorieResponse> AjouterCategorieAsync(Magasin.VenteProduit.AjouterCategorie request);
        
        // CODEGEN: Parameter 'client' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magasin.VenteProduit.ModifierClientResponse ModifierClient(Magasin.VenteProduit.ModifierClient request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.VenteProduit.ModifierClientResponse> ModifierClientAsync(Magasin.VenteProduit.ModifierClient request);
        
        // CODEGEN: Parameter 'Client' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magasin.VenteProduit.EnregistrerCommandeResponse EnregistrerCommande(Magasin.VenteProduit.EnregistrerCommande request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.VenteProduit.EnregistrerCommandeResponse> EnregistrerCommandeAsync(Magasin.VenteProduit.EnregistrerCommande request);
        
        // CODEGEN: Parameter 'produit' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magasin.VenteProduit.ModifierProduitResponse ModifierProduit(Magasin.VenteProduit.ModifierProduit request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.VenteProduit.ModifierProduitResponse> ModifierProduitAsync(Magasin.VenteProduit.ModifierProduit request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magasin.VenteProduit.SupprimerProduitParIdResponse SupprimerProduitParId(Magasin.VenteProduit.SupprimerProduitParId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.VenteProduit.SupprimerProduitParIdResponse> SupprimerProduitParIdAsync(Magasin.VenteProduit.SupprimerProduitParId request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Magasin.VenteProduit.ConsulterPanierResponse ConsulterPanier(Magasin.VenteProduit.ConsulterPanier request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Magasin.VenteProduit.ConsulterPanierResponse> ConsulterPanierAsync(Magasin.VenteProduit.ConsulterPanier request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.spring.ubp.com/")]
    public partial class produit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idProduitField;
        
        private bool idProduitFieldSpecified;
        
        private string designationField;
        
        private string descriptionField;
        
        private double prixField;
        
        private int quantiteField;
        
        private bool selectedField;
        
        private byte[] photoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long idProduit {
            get {
                return this.idProduitField;
            }
            set {
                this.idProduitField = value;
                this.RaisePropertyChanged("idProduit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProduitSpecified {
            get {
                return this.idProduitFieldSpecified;
            }
            set {
                this.idProduitFieldSpecified = value;
                this.RaisePropertyChanged("idProduitSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string designation {
            get {
                return this.designationField;
            }
            set {
                this.designationField = value;
                this.RaisePropertyChanged("designation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double prix {
            get {
                return this.prixField;
            }
            set {
                this.prixField = value;
                this.RaisePropertyChanged("prix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int quantite {
            get {
                return this.quantiteField;
            }
            set {
                this.quantiteField = value;
                this.RaisePropertyChanged("quantite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool selected {
            get {
                return this.selectedField;
            }
            set {
                this.selectedField = value;
                this.RaisePropertyChanged("selected");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=6)]
        public byte[] photo {
            get {
                return this.photoField;
            }
            set {
                this.photoField = value;
                this.RaisePropertyChanged("photo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.spring.ubp.com/")]
    public partial class commande : object, System.ComponentModel.INotifyPropertyChanged {
        
        private client clientField;
        
        private System.DateTime dateCommandeField;
        
        private bool dateCommandeFieldSpecified;
        
        private long idCommandeField;
        
        private bool idCommandeFieldSpecified;
        
        private ligneDeCommande[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public client client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
                this.RaisePropertyChanged("client");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime dateCommande {
            get {
                return this.dateCommandeField;
            }
            set {
                this.dateCommandeField = value;
                this.RaisePropertyChanged("dateCommande");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateCommandeSpecified {
            get {
                return this.dateCommandeFieldSpecified;
            }
            set {
                this.dateCommandeFieldSpecified = value;
                this.RaisePropertyChanged("dateCommandeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long idCommande {
            get {
                return this.idCommandeField;
            }
            set {
                this.idCommandeField = value;
                this.RaisePropertyChanged("idCommande");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCommandeSpecified {
            get {
                return this.idCommandeFieldSpecified;
            }
            set {
                this.idCommandeFieldSpecified = value;
                this.RaisePropertyChanged("idCommandeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("items", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public ligneDeCommande[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.spring.ubp.com/")]
    public partial class client : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idClientField;
        
        private bool idClientFieldSpecified;
        
        private string nomField;
        
        private string prenomField;
        
        private string adresseField;
        
        private string telField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long idClient {
            get {
                return this.idClientField;
            }
            set {
                this.idClientField = value;
                this.RaisePropertyChanged("idClient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idClientSpecified {
            get {
                return this.idClientFieldSpecified;
            }
            set {
                this.idClientFieldSpecified = value;
                this.RaisePropertyChanged("idClientSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                this.nomField = value;
                this.RaisePropertyChanged("nom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string prenom {
            get {
                return this.prenomField;
            }
            set {
                this.prenomField = value;
                this.RaisePropertyChanged("prenom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
                this.RaisePropertyChanged("adresse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string tel {
            get {
                return this.telField;
            }
            set {
                this.telField = value;
                this.RaisePropertyChanged("tel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.spring.ubp.com/")]
    public partial class ligneDeCommande : object, System.ComponentModel.INotifyPropertyChanged {
        
        private commande commandeField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private double prixField;
        
        private produit produitField;
        
        private int quantiteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public commande commande {
            get {
                return this.commandeField;
            }
            set {
                this.commandeField = value;
                this.RaisePropertyChanged("commande");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double prix {
            get {
                return this.prixField;
            }
            set {
                this.prixField = value;
                this.RaisePropertyChanged("prix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public produit produit {
            get {
                return this.produitField;
            }
            set {
                this.produitField = value;
                this.RaisePropertyChanged("produit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int quantite {
            get {
                return this.quantiteField;
            }
            set {
                this.quantiteField = value;
                this.RaisePropertyChanged("quantite");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.spring.ubp.com/")]
    public partial class panier : object, System.ComponentModel.INotifyPropertyChanged {
        
        private panierEntry[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public panierEntry[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.spring.ubp.com/")]
    public partial class panierEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long keyField;
        
        private bool keyFieldSpecified;
        
        private ligneDeCommande valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool keySpecified {
            get {
                return this.keyFieldSpecified;
            }
            set {
                this.keyFieldSpecified = value;
                this.RaisePropertyChanged("keySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ligneDeCommande value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.spring.ubp.com/")]
    public partial class categorie : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idCategorieField;
        
        private bool idCategorieFieldSpecified;
        
        private string nomField;
        
        private byte[] photoField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long idCategorie {
            get {
                return this.idCategorieField;
            }
            set {
                this.idCategorieField = value;
                this.RaisePropertyChanged("idCategorie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCategorieSpecified {
            get {
                return this.idCategorieFieldSpecified;
            }
            set {
                this.idCategorieFieldSpecified = value;
                this.RaisePropertyChanged("idCategorieSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                this.nomField = value;
                this.RaisePropertyChanged("nom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] photo {
            get {
                return this.photoField;
            }
            set {
                this.photoField = value;
                this.RaisePropertyChanged("photo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListerProduitParCategorie", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class ListerProduitParCategorie {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomCategorie;
        
        public ListerProduitParCategorie() {
        }
        
        public ListerProduitParCategorie(string nomCategorie) {
            this.nomCategorie = nomCategorie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListerProduitParCategorieResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class ListerProduitParCategorieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Magasin.VenteProduit.produit[] @return;
        
        public ListerProduitParCategorieResponse() {
        }
        
        public ListerProduitParCategorieResponse(Magasin.VenteProduit.produit[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListeDesClients", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class ListeDesClients {
        
        public ListeDesClients() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListeDesClientsResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class ListeDesClientsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Magasin.VenteProduit.client[] @return;
        
        public ListeDesClientsResponse() {
        }
        
        public ListeDesClientsResponse(Magasin.VenteProduit.client[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RechercherProduitParId", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class RechercherProduitParId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id;
        
        public RechercherProduitParId() {
        }
        
        public RechercherProduitParId(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RechercherProduitParIdResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class RechercherProduitParIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Magasin.VenteProduit.produit @return;
        
        public RechercherProduitParIdResponse() {
        }
        
        public RechercherProduitParIdResponse(Magasin.VenteProduit.produit @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListerProduitParMotCle", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class ListerProduitParMotCle {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MotCle;
        
        public ListerProduitParMotCle() {
        }
        
        public ListerProduitParMotCle(string MotCle) {
            this.MotCle = MotCle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListerProduitParMotCleResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class ListerProduitParMotCleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Magasin.VenteProduit.produit[] @return;
        
        public ListerProduitParMotCleResponse() {
        }
        
        public ListerProduitParMotCleResponse(Magasin.VenteProduit.produit[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListeDeProduits", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class ListeDeProduits {
        
        public ListeDeProduits() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListeDeProduitsResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class ListeDeProduitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Magasin.VenteProduit.produit[] @return;
        
        public ListeDeProduitsResponse() {
        }
        
        public ListeDeProduitsResponse(Magasin.VenteProduit.produit[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifierCategorie", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class ModifierCategorie {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Magasin.VenteProduit.categorie categorie;
        
        public ModifierCategorie() {
        }
        
        public ModifierCategorie(Magasin.VenteProduit.categorie categorie) {
            this.categorie = categorie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifierCategorieResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class ModifierCategorieResponse {
        
        public ModifierCategorieResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AjouterClient", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class AjouterClient {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Magasin.VenteProduit.client client;
        
        public AjouterClient() {
        }
        
        public AjouterClient(Magasin.VenteProduit.client client) {
            this.client = client;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AjouterClientResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class AjouterClientResponse {
        
        public AjouterClientResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SupprimerCategorie", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class SupprimerCategorie {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idCategorie;
        
        public SupprimerCategorie() {
        }
        
        public SupprimerCategorie(long idCategorie) {
            this.idCategorie = idCategorie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SupprimerCategorieResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class SupprimerCategorieResponse {
        
        public SupprimerCategorieResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AjouterProduit", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class AjouterProduit {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Magasin.VenteProduit.produit produit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idCategorie;
        
        public AjouterProduit() {
        }
        
        public AjouterProduit(Magasin.VenteProduit.produit produit, long idCategorie) {
            this.produit = produit;
            this.idCategorie = idCategorie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AjouterProduitResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class AjouterProduitResponse {
        
        public AjouterProduitResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RechercherClientParId", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class RechercherClientParId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idClient;
        
        public RechercherClientParId() {
        }
        
        public RechercherClientParId(long idClient) {
            this.idClient = idClient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RechercherClientParIdResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class RechercherClientParIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Magasin.VenteProduit.client @return;
        
        public RechercherClientParIdResponse() {
        }
        
        public RechercherClientParIdResponse(Magasin.VenteProduit.client @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AjouterCategorie", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class AjouterCategorie {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Magasin.VenteProduit.categorie categorie;
        
        public AjouterCategorie() {
        }
        
        public AjouterCategorie(Magasin.VenteProduit.categorie categorie) {
            this.categorie = categorie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AjouterCategorieResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class AjouterCategorieResponse {
        
        public AjouterCategorieResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifierClient", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class ModifierClient {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Magasin.VenteProduit.client client;
        
        public ModifierClient() {
        }
        
        public ModifierClient(Magasin.VenteProduit.client client) {
            this.client = client;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifierClientResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class ModifierClientResponse {
        
        public ModifierClientResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnregistrerCommande", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class EnregistrerCommande {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Magasin.VenteProduit.client Client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Magasin.VenteProduit.panier panier;
        
        public EnregistrerCommande() {
        }
        
        public EnregistrerCommande(Magasin.VenteProduit.client Client, Magasin.VenteProduit.panier panier) {
            this.Client = Client;
            this.panier = panier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnregistrerCommandeResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class EnregistrerCommandeResponse {
        
        public EnregistrerCommandeResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifierProduit", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class ModifierProduit {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Magasin.VenteProduit.produit produit;
        
        public ModifierProduit() {
        }
        
        public ModifierProduit(Magasin.VenteProduit.produit produit) {
            this.produit = produit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifierProduitResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class ModifierProduitResponse {
        
        public ModifierProduitResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SupprimerProduitParId", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class SupprimerProduitParId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id;
        
        public SupprimerProduitParId() {
        }
        
        public SupprimerProduitParId(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SupprimerProduitParIdResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class SupprimerProduitParIdResponse {
        
        public SupprimerProduitParIdResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsulterPanier", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class ConsulterPanier {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idclient;
        
        public ConsulterPanier() {
        }
        
        public ConsulterPanier(long idclient) {
            this.idclient = idclient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsulterPanierResponse", WrapperNamespace="http://ws.spring.ubp.com/", IsWrapped=true)]
    public partial class ConsulterPanierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.spring.ubp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Magasin.VenteProduit.ligneDeCommande[] @return;
        
        public ConsulterPanierResponse() {
        }
        
        public ConsulterPanierResponse(Magasin.VenteProduit.ligneDeCommande[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VenteProduitChannel : Magasin.VenteProduit.VenteProduit, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VenteProduitClient : System.ServiceModel.ClientBase<Magasin.VenteProduit.VenteProduit>, Magasin.VenteProduit.VenteProduit {
        
        public VenteProduitClient() {
        }
        
        public VenteProduitClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VenteProduitClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VenteProduitClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VenteProduitClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.VenteProduit.ListerProduitParCategorieResponse Magasin.VenteProduit.VenteProduit.ListerProduitParCategorie(Magasin.VenteProduit.ListerProduitParCategorie request) {
            return base.Channel.ListerProduitParCategorie(request);
        }
        
        public Magasin.VenteProduit.produit[] ListerProduitParCategorie(string nomCategorie) {
            Magasin.VenteProduit.ListerProduitParCategorie inValue = new Magasin.VenteProduit.ListerProduitParCategorie();
            inValue.nomCategorie = nomCategorie;
            Magasin.VenteProduit.ListerProduitParCategorieResponse retVal = ((Magasin.VenteProduit.VenteProduit)(this)).ListerProduitParCategorie(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.VenteProduit.ListerProduitParCategorieResponse> Magasin.VenteProduit.VenteProduit.ListerProduitParCategorieAsync(Magasin.VenteProduit.ListerProduitParCategorie request) {
            return base.Channel.ListerProduitParCategorieAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.VenteProduit.ListerProduitParCategorieResponse> ListerProduitParCategorieAsync(string nomCategorie) {
            Magasin.VenteProduit.ListerProduitParCategorie inValue = new Magasin.VenteProduit.ListerProduitParCategorie();
            inValue.nomCategorie = nomCategorie;
            return ((Magasin.VenteProduit.VenteProduit)(this)).ListerProduitParCategorieAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.VenteProduit.ListeDesClientsResponse Magasin.VenteProduit.VenteProduit.ListeDesClients(Magasin.VenteProduit.ListeDesClients request) {
            return base.Channel.ListeDesClients(request);
        }
        
        public Magasin.VenteProduit.client[] ListeDesClients() {
            Magasin.VenteProduit.ListeDesClients inValue = new Magasin.VenteProduit.ListeDesClients();
            Magasin.VenteProduit.ListeDesClientsResponse retVal = ((Magasin.VenteProduit.VenteProduit)(this)).ListeDesClients(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.VenteProduit.ListeDesClientsResponse> Magasin.VenteProduit.VenteProduit.ListeDesClientsAsync(Magasin.VenteProduit.ListeDesClients request) {
            return base.Channel.ListeDesClientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.VenteProduit.ListeDesClientsResponse> ListeDesClientsAsync() {
            Magasin.VenteProduit.ListeDesClients inValue = new Magasin.VenteProduit.ListeDesClients();
            return ((Magasin.VenteProduit.VenteProduit)(this)).ListeDesClientsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.VenteProduit.RechercherProduitParIdResponse Magasin.VenteProduit.VenteProduit.RechercherProduitParId(Magasin.VenteProduit.RechercherProduitParId request) {
            return base.Channel.RechercherProduitParId(request);
        }
        
        public Magasin.VenteProduit.produit RechercherProduitParId(long id) {
            Magasin.VenteProduit.RechercherProduitParId inValue = new Magasin.VenteProduit.RechercherProduitParId();
            inValue.id = id;
            Magasin.VenteProduit.RechercherProduitParIdResponse retVal = ((Magasin.VenteProduit.VenteProduit)(this)).RechercherProduitParId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.VenteProduit.RechercherProduitParIdResponse> Magasin.VenteProduit.VenteProduit.RechercherProduitParIdAsync(Magasin.VenteProduit.RechercherProduitParId request) {
            return base.Channel.RechercherProduitParIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.VenteProduit.RechercherProduitParIdResponse> RechercherProduitParIdAsync(long id) {
            Magasin.VenteProduit.RechercherProduitParId inValue = new Magasin.VenteProduit.RechercherProduitParId();
            inValue.id = id;
            return ((Magasin.VenteProduit.VenteProduit)(this)).RechercherProduitParIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.VenteProduit.ListerProduitParMotCleResponse Magasin.VenteProduit.VenteProduit.ListerProduitParMotCle(Magasin.VenteProduit.ListerProduitParMotCle request) {
            return base.Channel.ListerProduitParMotCle(request);
        }
        
        public Magasin.VenteProduit.produit[] ListerProduitParMotCle(string MotCle) {
            Magasin.VenteProduit.ListerProduitParMotCle inValue = new Magasin.VenteProduit.ListerProduitParMotCle();
            inValue.MotCle = MotCle;
            Magasin.VenteProduit.ListerProduitParMotCleResponse retVal = ((Magasin.VenteProduit.VenteProduit)(this)).ListerProduitParMotCle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.VenteProduit.ListerProduitParMotCleResponse> Magasin.VenteProduit.VenteProduit.ListerProduitParMotCleAsync(Magasin.VenteProduit.ListerProduitParMotCle request) {
            return base.Channel.ListerProduitParMotCleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.VenteProduit.ListerProduitParMotCleResponse> ListerProduitParMotCleAsync(string MotCle) {
            Magasin.VenteProduit.ListerProduitParMotCle inValue = new Magasin.VenteProduit.ListerProduitParMotCle();
            inValue.MotCle = MotCle;
            return ((Magasin.VenteProduit.VenteProduit)(this)).ListerProduitParMotCleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.VenteProduit.ListeDeProduitsResponse Magasin.VenteProduit.VenteProduit.ListeDeProduits(Magasin.VenteProduit.ListeDeProduits request) {
            return base.Channel.ListeDeProduits(request);
        }
        
        public Magasin.VenteProduit.produit[] ListeDeProduits() {
            Magasin.VenteProduit.ListeDeProduits inValue = new Magasin.VenteProduit.ListeDeProduits();
            Magasin.VenteProduit.ListeDeProduitsResponse retVal = ((Magasin.VenteProduit.VenteProduit)(this)).ListeDeProduits(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.VenteProduit.ListeDeProduitsResponse> Magasin.VenteProduit.VenteProduit.ListeDeProduitsAsync(Magasin.VenteProduit.ListeDeProduits request) {
            return base.Channel.ListeDeProduitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.VenteProduit.ListeDeProduitsResponse> ListeDeProduitsAsync() {
            Magasin.VenteProduit.ListeDeProduits inValue = new Magasin.VenteProduit.ListeDeProduits();
            return ((Magasin.VenteProduit.VenteProduit)(this)).ListeDeProduitsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.VenteProduit.ModifierCategorieResponse Magasin.VenteProduit.VenteProduit.ModifierCategorie(Magasin.VenteProduit.ModifierCategorie request) {
            return base.Channel.ModifierCategorie(request);
        }
        
        public void ModifierCategorie(Magasin.VenteProduit.categorie categorie) {
            Magasin.VenteProduit.ModifierCategorie inValue = new Magasin.VenteProduit.ModifierCategorie();
            inValue.categorie = categorie;
            Magasin.VenteProduit.ModifierCategorieResponse retVal = ((Magasin.VenteProduit.VenteProduit)(this)).ModifierCategorie(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.VenteProduit.ModifierCategorieResponse> Magasin.VenteProduit.VenteProduit.ModifierCategorieAsync(Magasin.VenteProduit.ModifierCategorie request) {
            return base.Channel.ModifierCategorieAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.VenteProduit.ModifierCategorieResponse> ModifierCategorieAsync(Magasin.VenteProduit.categorie categorie) {
            Magasin.VenteProduit.ModifierCategorie inValue = new Magasin.VenteProduit.ModifierCategorie();
            inValue.categorie = categorie;
            return ((Magasin.VenteProduit.VenteProduit)(this)).ModifierCategorieAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.VenteProduit.AjouterClientResponse Magasin.VenteProduit.VenteProduit.AjouterClient(Magasin.VenteProduit.AjouterClient request) {
            return base.Channel.AjouterClient(request);
        }
        
        public void AjouterClient(Magasin.VenteProduit.client client) {
            Magasin.VenteProduit.AjouterClient inValue = new Magasin.VenteProduit.AjouterClient();
            inValue.client = client;
            Magasin.VenteProduit.AjouterClientResponse retVal = ((Magasin.VenteProduit.VenteProduit)(this)).AjouterClient(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.VenteProduit.AjouterClientResponse> Magasin.VenteProduit.VenteProduit.AjouterClientAsync(Magasin.VenteProduit.AjouterClient request) {
            return base.Channel.AjouterClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.VenteProduit.AjouterClientResponse> AjouterClientAsync(Magasin.VenteProduit.client client) {
            Magasin.VenteProduit.AjouterClient inValue = new Magasin.VenteProduit.AjouterClient();
            inValue.client = client;
            return ((Magasin.VenteProduit.VenteProduit)(this)).AjouterClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.VenteProduit.SupprimerCategorieResponse Magasin.VenteProduit.VenteProduit.SupprimerCategorie(Magasin.VenteProduit.SupprimerCategorie request) {
            return base.Channel.SupprimerCategorie(request);
        }
        
        public void SupprimerCategorie(long idCategorie) {
            Magasin.VenteProduit.SupprimerCategorie inValue = new Magasin.VenteProduit.SupprimerCategorie();
            inValue.idCategorie = idCategorie;
            Magasin.VenteProduit.SupprimerCategorieResponse retVal = ((Magasin.VenteProduit.VenteProduit)(this)).SupprimerCategorie(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.VenteProduit.SupprimerCategorieResponse> Magasin.VenteProduit.VenteProduit.SupprimerCategorieAsync(Magasin.VenteProduit.SupprimerCategorie request) {
            return base.Channel.SupprimerCategorieAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.VenteProduit.SupprimerCategorieResponse> SupprimerCategorieAsync(long idCategorie) {
            Magasin.VenteProduit.SupprimerCategorie inValue = new Magasin.VenteProduit.SupprimerCategorie();
            inValue.idCategorie = idCategorie;
            return ((Magasin.VenteProduit.VenteProduit)(this)).SupprimerCategorieAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.VenteProduit.AjouterProduitResponse Magasin.VenteProduit.VenteProduit.AjouterProduit(Magasin.VenteProduit.AjouterProduit request) {
            return base.Channel.AjouterProduit(request);
        }
        
        public void AjouterProduit(Magasin.VenteProduit.produit produit, long idCategorie) {
            Magasin.VenteProduit.AjouterProduit inValue = new Magasin.VenteProduit.AjouterProduit();
            inValue.produit = produit;
            inValue.idCategorie = idCategorie;
            Magasin.VenteProduit.AjouterProduitResponse retVal = ((Magasin.VenteProduit.VenteProduit)(this)).AjouterProduit(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.VenteProduit.AjouterProduitResponse> Magasin.VenteProduit.VenteProduit.AjouterProduitAsync(Magasin.VenteProduit.AjouterProduit request) {
            return base.Channel.AjouterProduitAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.VenteProduit.AjouterProduitResponse> AjouterProduitAsync(Magasin.VenteProduit.produit produit, long idCategorie) {
            Magasin.VenteProduit.AjouterProduit inValue = new Magasin.VenteProduit.AjouterProduit();
            inValue.produit = produit;
            inValue.idCategorie = idCategorie;
            return ((Magasin.VenteProduit.VenteProduit)(this)).AjouterProduitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.VenteProduit.RechercherClientParIdResponse Magasin.VenteProduit.VenteProduit.RechercherClientParId(Magasin.VenteProduit.RechercherClientParId request) {
            return base.Channel.RechercherClientParId(request);
        }
        
        public Magasin.VenteProduit.client RechercherClientParId(long idClient) {
            Magasin.VenteProduit.RechercherClientParId inValue = new Magasin.VenteProduit.RechercherClientParId();
            inValue.idClient = idClient;
            Magasin.VenteProduit.RechercherClientParIdResponse retVal = ((Magasin.VenteProduit.VenteProduit)(this)).RechercherClientParId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.VenteProduit.RechercherClientParIdResponse> Magasin.VenteProduit.VenteProduit.RechercherClientParIdAsync(Magasin.VenteProduit.RechercherClientParId request) {
            return base.Channel.RechercherClientParIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.VenteProduit.RechercherClientParIdResponse> RechercherClientParIdAsync(long idClient) {
            Magasin.VenteProduit.RechercherClientParId inValue = new Magasin.VenteProduit.RechercherClientParId();
            inValue.idClient = idClient;
            return ((Magasin.VenteProduit.VenteProduit)(this)).RechercherClientParIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.VenteProduit.AjouterCategorieResponse Magasin.VenteProduit.VenteProduit.AjouterCategorie(Magasin.VenteProduit.AjouterCategorie request) {
            return base.Channel.AjouterCategorie(request);
        }
        
        public void AjouterCategorie(Magasin.VenteProduit.categorie categorie) {
            Magasin.VenteProduit.AjouterCategorie inValue = new Magasin.VenteProduit.AjouterCategorie();
            inValue.categorie = categorie;
            Magasin.VenteProduit.AjouterCategorieResponse retVal = ((Magasin.VenteProduit.VenteProduit)(this)).AjouterCategorie(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.VenteProduit.AjouterCategorieResponse> Magasin.VenteProduit.VenteProduit.AjouterCategorieAsync(Magasin.VenteProduit.AjouterCategorie request) {
            return base.Channel.AjouterCategorieAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.VenteProduit.AjouterCategorieResponse> AjouterCategorieAsync(Magasin.VenteProduit.categorie categorie) {
            Magasin.VenteProduit.AjouterCategorie inValue = new Magasin.VenteProduit.AjouterCategorie();
            inValue.categorie = categorie;
            return ((Magasin.VenteProduit.VenteProduit)(this)).AjouterCategorieAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.VenteProduit.ModifierClientResponse Magasin.VenteProduit.VenteProduit.ModifierClient(Magasin.VenteProduit.ModifierClient request) {
            return base.Channel.ModifierClient(request);
        }
        
        public void ModifierClient(Magasin.VenteProduit.client client) {
            Magasin.VenteProduit.ModifierClient inValue = new Magasin.VenteProduit.ModifierClient();
            inValue.client = client;
            Magasin.VenteProduit.ModifierClientResponse retVal = ((Magasin.VenteProduit.VenteProduit)(this)).ModifierClient(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.VenteProduit.ModifierClientResponse> Magasin.VenteProduit.VenteProduit.ModifierClientAsync(Magasin.VenteProduit.ModifierClient request) {
            return base.Channel.ModifierClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.VenteProduit.ModifierClientResponse> ModifierClientAsync(Magasin.VenteProduit.client client) {
            Magasin.VenteProduit.ModifierClient inValue = new Magasin.VenteProduit.ModifierClient();
            inValue.client = client;
            return ((Magasin.VenteProduit.VenteProduit)(this)).ModifierClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.VenteProduit.EnregistrerCommandeResponse Magasin.VenteProduit.VenteProduit.EnregistrerCommande(Magasin.VenteProduit.EnregistrerCommande request) {
            return base.Channel.EnregistrerCommande(request);
        }
        
        public void EnregistrerCommande(Magasin.VenteProduit.client Client, Magasin.VenteProduit.panier panier) {
            Magasin.VenteProduit.EnregistrerCommande inValue = new Magasin.VenteProduit.EnregistrerCommande();
            inValue.Client = Client;
            inValue.panier = panier;
            Magasin.VenteProduit.EnregistrerCommandeResponse retVal = ((Magasin.VenteProduit.VenteProduit)(this)).EnregistrerCommande(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.VenteProduit.EnregistrerCommandeResponse> Magasin.VenteProduit.VenteProduit.EnregistrerCommandeAsync(Magasin.VenteProduit.EnregistrerCommande request) {
            return base.Channel.EnregistrerCommandeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.VenteProduit.EnregistrerCommandeResponse> EnregistrerCommandeAsync(Magasin.VenteProduit.client Client, Magasin.VenteProduit.panier panier) {
            Magasin.VenteProduit.EnregistrerCommande inValue = new Magasin.VenteProduit.EnregistrerCommande();
            inValue.Client = Client;
            inValue.panier = panier;
            return ((Magasin.VenteProduit.VenteProduit)(this)).EnregistrerCommandeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.VenteProduit.ModifierProduitResponse Magasin.VenteProduit.VenteProduit.ModifierProduit(Magasin.VenteProduit.ModifierProduit request) {
            return base.Channel.ModifierProduit(request);
        }
        
        public void ModifierProduit(Magasin.VenteProduit.produit produit) {
            Magasin.VenteProduit.ModifierProduit inValue = new Magasin.VenteProduit.ModifierProduit();
            inValue.produit = produit;
            Magasin.VenteProduit.ModifierProduitResponse retVal = ((Magasin.VenteProduit.VenteProduit)(this)).ModifierProduit(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.VenteProduit.ModifierProduitResponse> Magasin.VenteProduit.VenteProduit.ModifierProduitAsync(Magasin.VenteProduit.ModifierProduit request) {
            return base.Channel.ModifierProduitAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.VenteProduit.ModifierProduitResponse> ModifierProduitAsync(Magasin.VenteProduit.produit produit) {
            Magasin.VenteProduit.ModifierProduit inValue = new Magasin.VenteProduit.ModifierProduit();
            inValue.produit = produit;
            return ((Magasin.VenteProduit.VenteProduit)(this)).ModifierProduitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.VenteProduit.SupprimerProduitParIdResponse Magasin.VenteProduit.VenteProduit.SupprimerProduitParId(Magasin.VenteProduit.SupprimerProduitParId request) {
            return base.Channel.SupprimerProduitParId(request);
        }
        
        public void SupprimerProduitParId(long id) {
            Magasin.VenteProduit.SupprimerProduitParId inValue = new Magasin.VenteProduit.SupprimerProduitParId();
            inValue.id = id;
            Magasin.VenteProduit.SupprimerProduitParIdResponse retVal = ((Magasin.VenteProduit.VenteProduit)(this)).SupprimerProduitParId(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.VenteProduit.SupprimerProduitParIdResponse> Magasin.VenteProduit.VenteProduit.SupprimerProduitParIdAsync(Magasin.VenteProduit.SupprimerProduitParId request) {
            return base.Channel.SupprimerProduitParIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.VenteProduit.SupprimerProduitParIdResponse> SupprimerProduitParIdAsync(long id) {
            Magasin.VenteProduit.SupprimerProduitParId inValue = new Magasin.VenteProduit.SupprimerProduitParId();
            inValue.id = id;
            return ((Magasin.VenteProduit.VenteProduit)(this)).SupprimerProduitParIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magasin.VenteProduit.ConsulterPanierResponse Magasin.VenteProduit.VenteProduit.ConsulterPanier(Magasin.VenteProduit.ConsulterPanier request) {
            return base.Channel.ConsulterPanier(request);
        }
        
        public Magasin.VenteProduit.ligneDeCommande[] ConsulterPanier(long idclient) {
            Magasin.VenteProduit.ConsulterPanier inValue = new Magasin.VenteProduit.ConsulterPanier();
            inValue.idclient = idclient;
            Magasin.VenteProduit.ConsulterPanierResponse retVal = ((Magasin.VenteProduit.VenteProduit)(this)).ConsulterPanier(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magasin.VenteProduit.ConsulterPanierResponse> Magasin.VenteProduit.VenteProduit.ConsulterPanierAsync(Magasin.VenteProduit.ConsulterPanier request) {
            return base.Channel.ConsulterPanierAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magasin.VenteProduit.ConsulterPanierResponse> ConsulterPanierAsync(long idclient) {
            Magasin.VenteProduit.ConsulterPanier inValue = new Magasin.VenteProduit.ConsulterPanier();
            inValue.idclient = idclient;
            return ((Magasin.VenteProduit.VenteProduit)(this)).ConsulterPanierAsync(inValue);
        }
    }
}
