//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace purchase_app.purchase_service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="purchase_service.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément HelloWorldResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        purchase_app.purchase_service.HelloWorldResponse HelloWorld(purchase_app.purchase_service.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<purchase_app.purchase_service.HelloWorldResponse> HelloWorldAsync(purchase_app.purchase_service.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Addition", ReplyAction="*")]
        int Addition(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Addition", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AdditionAsync(int a, int b);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément numAccount de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BankWire", ReplyAction="*")]
        purchase_app.purchase_service.BankWireResponse BankWire(purchase_app.purchase_service.BankWireRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BankWire", ReplyAction="*")]
        System.Threading.Tasks.Task<purchase_app.purchase_service.BankWireResponse> BankWireAsync(purchase_app.purchase_service.BankWireRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public purchase_app.purchase_service.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(purchase_app.purchase_service.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public purchase_app.purchase_service.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(purchase_app.purchase_service.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BankWireRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BankWire", Namespace="http://tempuri.org/", Order=0)]
        public purchase_app.purchase_service.BankWireRequestBody Body;
        
        public BankWireRequest() {
        }
        
        public BankWireRequest(purchase_app.purchase_service.BankWireRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BankWireRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numAccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string movement;
        
        public BankWireRequestBody() {
        }
        
        public BankWireRequestBody(string numAccount, int amount, string movement) {
            this.numAccount = numAccount;
            this.amount = amount;
            this.movement = movement;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BankWireResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BankWireResponse", Namespace="http://tempuri.org/", Order=0)]
        public purchase_app.purchase_service.BankWireResponseBody Body;
        
        public BankWireResponse() {
        }
        
        public BankWireResponse(purchase_app.purchase_service.BankWireResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BankWireResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BankWireResult;
        
        public BankWireResponseBody() {
        }
        
        public BankWireResponseBody(string BankWireResult) {
            this.BankWireResult = BankWireResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : purchase_app.purchase_service.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<purchase_app.purchase_service.WebServiceSoap>, purchase_app.purchase_service.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        purchase_app.purchase_service.HelloWorldResponse purchase_app.purchase_service.WebServiceSoap.HelloWorld(purchase_app.purchase_service.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            purchase_app.purchase_service.HelloWorldRequest inValue = new purchase_app.purchase_service.HelloWorldRequest();
            inValue.Body = new purchase_app.purchase_service.HelloWorldRequestBody();
            purchase_app.purchase_service.HelloWorldResponse retVal = ((purchase_app.purchase_service.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<purchase_app.purchase_service.HelloWorldResponse> purchase_app.purchase_service.WebServiceSoap.HelloWorldAsync(purchase_app.purchase_service.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<purchase_app.purchase_service.HelloWorldResponse> HelloWorldAsync() {
            purchase_app.purchase_service.HelloWorldRequest inValue = new purchase_app.purchase_service.HelloWorldRequest();
            inValue.Body = new purchase_app.purchase_service.HelloWorldRequestBody();
            return ((purchase_app.purchase_service.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Addition(int a, int b) {
            return base.Channel.Addition(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AdditionAsync(int a, int b) {
            return base.Channel.AdditionAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        purchase_app.purchase_service.BankWireResponse purchase_app.purchase_service.WebServiceSoap.BankWire(purchase_app.purchase_service.BankWireRequest request) {
            return base.Channel.BankWire(request);
        }
        
        public string BankWire(string numAccount, int amount, string movement) {
            purchase_app.purchase_service.BankWireRequest inValue = new purchase_app.purchase_service.BankWireRequest();
            inValue.Body = new purchase_app.purchase_service.BankWireRequestBody();
            inValue.Body.numAccount = numAccount;
            inValue.Body.amount = amount;
            inValue.Body.movement = movement;
            purchase_app.purchase_service.BankWireResponse retVal = ((purchase_app.purchase_service.WebServiceSoap)(this)).BankWire(inValue);
            return retVal.Body.BankWireResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<purchase_app.purchase_service.BankWireResponse> purchase_app.purchase_service.WebServiceSoap.BankWireAsync(purchase_app.purchase_service.BankWireRequest request) {
            return base.Channel.BankWireAsync(request);
        }
        
        public System.Threading.Tasks.Task<purchase_app.purchase_service.BankWireResponse> BankWireAsync(string numAccount, int amount, string movement) {
            purchase_app.purchase_service.BankWireRequest inValue = new purchase_app.purchase_service.BankWireRequest();
            inValue.Body = new purchase_app.purchase_service.BankWireRequestBody();
            inValue.Body.numAccount = numAccount;
            inValue.Body.amount = amount;
            inValue.Body.movement = movement;
            return ((purchase_app.purchase_service.WebServiceSoap)(this)).BankWireAsync(inValue);
        }
    }
}
